config/routes.rb
Thrifter::Application.routes.draw do

  # Admin backend
  namespace :admin do
    root :to => "admin#homepage", as: :root

    resources :brands, except: :show

    resources :products, except: :show do
      resources :photos, except: [:show], controller: "product_photos" do
        collection { post :sort }
      end

      resources :replacements, only: [:index, :create, :destroy], controller: "product_replacements"

      resources :params, controller: "product_param_items"

      resources :categorizations, controller: "product_categorizations", only: [:index, :destroy] do
        collection do
          post :add_shop_to
          get :edit_alternative
          put :update_alternative
        end
        member do
          get :edit_preferred
        end
      end
    end

    resources :param_templates do
      resources :groups, controller: "param_groups", except: :index do
        collection { post :sort }
      end
      resources :param_items
    end

    resources :payment_methods
    resources :shipping_methods do
      collection { post :sort }
    end
    
    resources :shops, except: :show do
      member do
        get :deletion_confirmation
      end

      resources :news_items, except: :show
      resources :categories, except: :show
      resources :articles, except: :show
    end

    resources :documents

    # Admistation of categories - choose which shop's categories to administrate
    match "kategorie/vyber-obchodu" => "categories#choose_shop", as: "categories"
    match "novinky/vyber-obchodu" => "news_items#choose_shop", as: "news_items"
    match "clanky/vyber-obchodu" => "articles#choose_shop", as: "articles"
  end

  # Application frontend
  root :to => "root#index"

  resource :cart, path: "kosik", controller: "cart", only: [:show, :create, :update, :destroy] do
    collection { get :add_product, path: "vlozeni" }
  end

  resource :order, path: "objednavka", controller: "order", path_names: {edit: "uprava"}, only: [:show, :update] do
    collection {
      put :complete
      get :completed, path: "dokonceni"
    }
  end

  match "/objednavka/:order_token" => "order#overview"

  match "/:category_url/:product_url(/:section)" => "products#show"
  match "/:category_url/"             => "categories#index"
end

app/models/article.rb
class Article < ActiveRecord::Base

  # Associations
  has_and_belongs_to_many :categories, join_table: :category_articles
  has_many :shops, through: :categories

  transliterate_permalink :url

  default_scope -> { order(:name) }

  # Validations
  validates :name,
            presence: true,
            length: {maximum: 100}

  validates :url,
            presence: true,
            length: {maximum: 100}

  validates :title,
            presence: true,
            length: {maximum: 250}

  validates :content,
            presence: true

  validates :summary,
            presence: true

  validates :categories,
            presence: true
end

app/controllers/admin/articles_controller.rb
# encoding: UTF-8

module Admin
  class ArticlesController < AdminController

    def choose_shop
    end

    def index
    end

    def new
    end

    def create
      if article.save
        redirect_to admin_shop_articles_url(shop), :notice => "Článek #{article.name} byl vytvořen"
      else
        flash.now[:error] = "Chyba při vytváření článku"
        render "new"
      end
    end

    def edit
    end

    def update
      if article.update_attributes(params[:article])
        redirect_to admin_shop_articles_url(shop), :notice => "Článek #{article.name} byl upraven"
      else
        flash.now[:error] = "Článek nebylo možné uložit"
        render "edit"
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Nelze najít daný článek"
      redirect_to admin_shop_articles_url(shop)
    end

    def destroy
      article.destroy
      flash[:notice] = "Článek #{article.name} byl smazán"
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Nelze najít daný článek"
    ensure
      redirect_to admin_shop_articles_url(shop)
    end

    private

    def article
      @article ||= params[:id] ? articles.find(params[:id]) : articles.new(params[:article])
    end

    helper_method :article

    def articles
      @articles ||= shop.articles
    end

    helper_method :articles

    def articles_paginated
      @articles_paginated ||= Kaminari.paginate_array(articles.all).page params[:page]
    end

    helper_method :articles_paginated

    def shop
      @shop ||= Shop.find(params[:shop_id])
    end

    helper_method :shop
  end
end

app/views/admin/articles/_form.html.haml
= semantic_form_for([:admin, shop, article]) do |f|
  = f.input :name
  = f.input :url, suggest_url: true
  = f.input :title
  = f.input :summary
  = f.input :content
  = f.inputs "Přiřazen ke kategoriím" do
    = category_select_for_shop(shop, f, {})

  = f.actions do
    = f.submit

app/views/admin/articles/choose_shop.html.haml
%h2 Články
%strong Vyberte obchod, ve kterém chcete spravovat články
%ul
  - for shop in Shop.all
    %li= link_to shop.name, admin_shop_articles_path(shop)

app/views/admin/articles/edit.html.haml
%h2 Úprava článku #{article.name}
= render "form"

app/views/admin/articles/index.html.haml
%h2 Články v obchodu #{shop.name}

%ul.action_links
  %li.create_new= link_to "Přidat nový článek", new_admin_shop_article_path(shop)

- unless articles_paginated.blank?
  %h3.panel Seznam článků

  %table#articles.table_overview
    %thead
      %tr
        %th Název
        %th Přiřazen ke kategorii
        %td Akce
    %tbody
      - for article in articles_paginated
        %tr{class: cycle("odd", "even")}
          %th= article.name
          %td= article.categories.collect(&:plural_name).to_sentence
          %td
            %ul.actions
              %li.edit= link_to "Upravit", edit_admin_shop_article_path(shop, article)
              %li.delete= link_to "Smazat", admin_shop_article_path(shop, article), method: :delete, confirm: "Opravdu smazat článek #{article.name}?"

  = paginate articles_paginated

- else
  .empty_set
    Zatím nejsou vytvořeny žádné články

app/views/admin/articles/new.html.haml
%h2 Nový článek
= render "form"