config/routes.rb
Thrifter::Application.routes.draw do

  # Admin backend
  namespace :admin do
    root :to => "admin#homepage", as: :root

    resources :brands, except: :show

    resources :products, except: :show do
      resources :photos, except: [:show], controller: "product_photos" do
        collection { post :sort }
      end

      resources :replacements, only: [:index, :create, :destroy], controller: "product_replacements"

      resources :params, controller: "product_param_items"

      resources :categorizations, controller: "product_categorizations", only: [:index, :destroy] do
        collection do
          post :add_shop_to
          get :edit_alternative
          put :update_alternative
        end
        member do
          get :edit_preferred
        end
      end
    end

    resources :param_templates do
      resources :groups, controller: "param_groups", except: :index do
        collection { post :sort }
      end
      resources :param_items
    end

    resources :payment_methods
    resources :shipping_methods do
      collection { post :sort }
    end
    
    resources :shops, except: :show do
      member do
        get :deletion_confirmation
      end

      resources :news_items, except: :show
      resources :categories, except: :show
      resources :articles, except: :show
    end

    resources :documents

    # Admistation of categories - choose which shop's categories to administrate
    match "kategorie/vyber-obchodu" => "categories#choose_shop", as: "categories"
    match "novinky/vyber-obchodu" => "news_items#choose_shop", as: "news_items"
    match "clanky/vyber-obchodu" => "articles#choose_shop", as: "articles"
  end

  # Application frontend
  root :to => "root#index"

  resource :cart, path: "kosik", controller: "cart", only: [:show, :create, :update, :destroy] do
    collection { get :add_product, path: "vlozeni" }
  end

  resource :order, path: "objednavka", controller: "order", path_names: {edit: "uprava"}, only: [:show, :update] do
    collection {
      put :complete
      get :completed, path: "dokonceni"
    }
  end

  match "/objednavka/:order_token" => "order#overview"

  match "/:category_url/:product_url(/:section)" => "products#show"
  match "/:category_url/"             => "categories#index"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  # Associations
  has_many :products

  transliterate_permalink :url

  default_scope -> { order(:name) }

  # Validations
  validates :name,
            presence: true,
            length: {maximum: 30}

  validates :url,
            presence: true,
            length: {maximum: 30},
            uniqueness: true
end

app/controllers/admin/brands_controller.rb
# encoding: UTF-8

module Admin
  class BrandsController < AdminController
    def index
    end

    def new
    end

    def create
      if brand.save
        redirect_to admin_brands_url, notice: "Značka #{brand.name} byla vytvořena"
      else
        flash.now[:error] = "Chyba při vytváření nové značky"
        render :action => :new
      end
    end

    def edit
    end

    def update
      if brand.update_attributes(params[:brand])
        redirect_to admin_brands_url, notice: "Značka #{brand.name} byla upravena"
      else
        flash.now[:error] = "Chyba při upravování značky #{brand.name}"
        render :action => :edit
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Neexistující značka"
      redirect_to admin_brands_url
    end

    def destroy
      brand.destroy
      flash[:notice] = "Značka #{brand.name} byla smazána"
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Neznámá značka"
    ensure
      redirect_to admin_brands_url
    end

    private

    def brand
      @brand ||= params[:id] ? Brand.find(params[:id]) : Brand.new(params[:brand])
    end

    helper_method :brand

    def brands
      @brands ||= Brand.page params[:page]
    end

    helper_method :brands
  end
end

app/views/admin/brands/_form.html.haml
= semantic_form_for([:admin, brand]) do |f|
  = f.input :name
  = f.input :url, suggest_url: true
  = f.input :description

  = f.actions do
    = f.submit

app/views/admin/brands/edit.html.haml
%h2 Úprava značky #{brand.name}
= render "form"

app/views/admin/brands/index.html.haml
%h2 Značky
%ul.action_links
  %li.create_new= link_to "Přidat novou značku", new_admin_brand_path

- unless brands.empty?
  %h3.panel Seznam značek

  %table#brands.table_overview
    %thead
      %tr
        %th Název značky
        %td Akce
    %tbody
      - for brand in brands
        %tr{class: cycle("odd", "even")}
          %th= brand.name
          %td
            %ul.actions
              %li.edit= link_to "Upravit", edit_admin_brand_path(brand)
              %li.delete= link_to "Smazat", admin_brand_path(brand), method: :delete, confirm: "Opravdu smazat značku #{brand.name}?"

- else
  .empty_set
    Zatím nejsou vytvořeny žádné značky

app/views/admin/brands/new.html.haml
%h2 Nová značka
= render "form"