config/routes.rb
Thrifter::Application.routes.draw do

  # Admin backend
  namespace :admin do
    root :to => "admin#homepage", as: :root

    resources :brands, except: :show

    resources :products, except: :show do
      resources :photos, except: [:show], controller: "product_photos" do
        collection { post :sort }
      end

      resources :replacements, only: [:index, :create, :destroy], controller: "product_replacements"

      resources :params, controller: "product_param_items"

      resources :categorizations, controller: "product_categorizations", only: [:index, :destroy] do
        collection do
          post :add_shop_to
          get :edit_alternative
          put :update_alternative
        end
        member do
          get :edit_preferred
        end
      end
    end

    resources :param_templates do
      resources :groups, controller: "param_groups", except: :index do
        collection { post :sort }
      end
      resources :param_items
    end

    resources :payment_methods
    resources :shipping_methods do
      collection { post :sort }
    end
    
    resources :shops, except: :show do
      member do
        get :deletion_confirmation
      end

      resources :news_items, except: :show
      resources :categories, except: :show
      resources :articles, except: :show
    end

    resources :documents

    # Admistation of categories - choose which shop's categories to administrate
    match "kategorie/vyber-obchodu" => "categories#choose_shop", as: "categories"
    match "novinky/vyber-obchodu" => "news_items#choose_shop", as: "news_items"
    match "clanky/vyber-obchodu" => "articles#choose_shop", as: "articles"
  end

  # Application frontend
  root :to => "root#index"

  resource :cart, path: "kosik", controller: "cart", only: [:show, :create, :update, :destroy] do
    collection { get :add_product, path: "vlozeni" }
  end

  resource :order, path: "objednavka", controller: "order", path_names: {edit: "uprava"}, only: [:show, :update] do
    collection {
      put :complete
      get :completed, path: "dokonceni"
    }
  end

  match "/objednavka/:order_token" => "order#overview"

  match "/:category_url/:product_url(/:section)" => "products#show"
  match "/:category_url/"             => "categories#index"
end

app/controllers/admin/product_categorizations_controller.rb
# encoding: UTF-8

module Admin
  class ProductCategorizationsController < AdminController
    before_filter :only_in_shop_context, only: [:edit_alternative, :update_alternative]

    def index
    end

    def edit_alternative
    end

    def update_alternative
      product_categorizations = ProductShopCategorizations.new(product, shop)
      product_categorizations.set_alternative_categories!(params[:product][:category_ids])
      redirect_to admin_product_categorizations_url(product)
    end

    def edit_preferred
      unless categorization.preferred
        flash[:error] = "Chyba při zobrazení editace hlavní kategorie"
        redirect_to admin_product_categorizations_path(product)
      end
    end


    private

    # Product
    def product
      @product ||= Product.find(params[:product_id])
    end

    helper_method :product

    # Categorizations colletion
    def categorizations
      product.categorizations
    end

    helper_method :categorizations

    # Categorization - for member action
    def categorization
      categorizations.find(params[:id])
    end

    helper_method :categorization

    # Shop - if defined in params
    def shop
      @shop ||= params[:shop_id] && Shop.find(params[:shop_id])
    end

    helper_method :shop

    # Halt filter chain if shop_id is not present in params
    def only_in_shop_context
      unless shop.present?
        flash[:error] = "Musíte specifikovat obchod"
        redirect_to(admin_product_categorizations_url(product))
        false
      end
      true
    end
  end
end

app/helpers/admin/product_categorizations_helper.rb
module Admin::ProductCategorizationsHelper
  def assigned_shops
    shop_ids = product.categorizations.joins(:category).pluck(:shop_id).uniq
    Shop.where(id: shop_ids)
  end

  def preferred_category_in_shop(shop)
    preferred_categorization_in_shop(shop).category
  end

  def preferred_categorization_in_shop(shop)
    product.categorizations.preferred.in_shop(shop).first
  end

  def alternative_categories_in_shop(shop)
    product.alternative_categories.where(shop_id: shop.id)
  end

  def shops
    Shop.all
  end

  def disabled_categories_for_product_in_shop(shop)
    (descendants_of_assigned_categories +
        preferred_category(shop) +
        categories_with_other_param_template(shop)).flatten.uniq
  end

  def disabled_categories_preferred_categorization(categorization)
    shop = categorization.category.shop
    (descendants_of_assigned_categories + categories_with_other_param_template(shop)).flatten.uniq
  end

  def descendants_of_assigned_categories
    product.categories.map { |category| category.descendants.pluck(:id) }
  end

  def preferred_category(shop)
    product.categorizations.preferred.in_shop(shop).pluck(:category_id)
  end

  def categories_with_other_param_template(shop)
    Category.in_shop(shop).
        where(category_type: :product_list).
        where("param_template_id != ? || param_template_id IS NULL", product.param_template.id).map do |category|
      category.self_and_descendants.pluck(:id)
    end
  end
end

app/views/admin/product_categorizations/_alternative_categories_form.html.haml
= semantic_form_for([:admin, product], url: update_alternative_admin_product_categorizations_path(shop_id: shop.id)) do |f|
  = category_select_for_shop(shop, f, disabled: disabled_categories_for_product_in_shop(shop), show_if: [:product_list?, :additional?])
  = f.actions do
    = f.submit "Uložit alternativní kategorie"

app/views/admin/product_categorizations/_form.html.haml
= semantic_form_for([:admin, product], url: update_shop_admin_product_categorizations_path(shop_id: shop.id)) do |f|
  = category_select_for_shop(shop, f, disabled: disabled_categories_for_product_in_shop(shop), show_if: [:product_list?, :additional?])
  = f.actions do
    = f.submit "Uložit alternativní kategorie"

app/views/admin/product_categorizations/_preferred_category.html.haml
%strong= preferred_category.plural_name
%span.path_to_node= preferred_category.path_to_node

app/views/admin/product_categorizations/_preferred_category_form.html.haml
= semantic_form_for([:admin, product]) do |f|
  = category_select_for_shop(Shop.first, f,
                             show_if: [:product_list?, :additional?],
                             disabled: disabled_categories_preferred_categorization(categorization),
                             as_radio_buttons: true)
  = f.actions do
    = f.submit "Změnit hlavní kategorii"

app/views/admin/product_categorizations/edit_alternative.html.haml
%h2 Přiřazení produktu do nové kategorie v obchodu #{shop.name}
= render "alternative_categories_form"

app/views/admin/product_categorizations/edit_preferred.html.haml
%h2 Změna hlavní kategorie produktu

%strong Současná hlavní kategorie produktu:
= render :partial => "preferred_category", object: categorization.category

= render "preferred_category_form"

app/views/admin/product_categorizations/edit_shop.html.haml
%h2 Přiřazení produktu do nové kategorie v obchodu #{shop.name}
= render "alternative_categories_form"

app/views/admin/product_categorizations/index.html.haml
%h2 #{product.name} &ndash; zařazení do kategorií

#product_assigned_to_shops
  - for shop in assigned_shops
    = content_tag_for(:div, shop) do
      %h3= shop.name

      Hlavní kategorie:
      = render partial: "preferred_category", object: preferred_category_in_shop(shop)
      = link_to "Změnit hlavní kategorii",
        edit_preferred_admin_product_categorization_path(product, preferred_categorization_in_shop(shop))

      %h4 Alternativní kategorie
      %ul
        - for category in alternative_categories_in_shop(shop)
          %li
            %strong= category.plural_name
            %span.path_to_node= category.path_to_node
      = link_to "Upravit alternativní kategorie", edit_alternative_admin_product_categorizations_path(product, shop_id: shop.id)

  = form_tag(add_shop_to_admin_product_categorizations_path(product)) do
    %h3 Zařadit do dalšího obchodu
    = select_tag :shop_id, options_from_collection_for_select(shops, :id, :name)
    = submit_tag "Přidat do obchodu"